from io import StringIO
import pandas as pd  # type:ignore

openml_dict = [
    {
        "openml_dataset_id": 3,
        "name": "kr-vs-kp",
        "version": 1,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 6,
        "name": "letter",
        "version": 1,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 11,
        "name": "balance-scale",
        "version": 1,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 12,
        "name": "mfeat-factors",
        "version": 1,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 14,
        "name": "mfeat-fourier",
        "version": 1,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 15,
        "name": "breast-w",
        "version": 1,
        "target": "Class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 16,
        "name": "mfeat-karhunen",
        "version": 1,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 18,
        "name": "mfeat-morphological",
        "version": 1,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 22,
        "name": "mfeat-zernike",
        "version": 1,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 23,
        "name": "cmc",
        "version": 1,
        "target": "Contraceptive_method_used",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 28,
        "name": "optdigits",
        "version": 1,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 29,
        "name": "credit-approval",
        "version": 1,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 31,
        "name": "credit-g",
        "version": 1,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 32,
        "name": "pendigits",
        "version": 1,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 37,
        "name": "diabetes",
        "version": 1,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 44,
        "name": "spambase",
        "version": 1,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 46,
        "name": "splice",
        "version": 1,
        "target": "Class",
        "row_id_col": None,
        "ignore_cols": ["Instance_name"],
    },
    {
        "openml_dataset_id": 50,
        "name": "tic-tac-toe",
        "version": 1,
        "target": "Class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 54,
        "name": "vehicle",
        "version": 1,
        "target": "Class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 151,
        "name": "electricity",
        "version": 1,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 182,
        "name": "satimage",
        "version": 1,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 188,
        "name": "eucalyptus",
        "version": 1,
        "target": "Utility",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 38,
        "name": "sick",
        "version": 1,
        "target": "Class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 307,
        "name": "vowel",
        "version": 2,
        "target": "Class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 300,
        "name": "isolet",
        "version": 1,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 458,
        "name": "analcatdata_authorship",
        "version": 1,
        "target": "Author",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 469,
        "name": "analcatdata_dmft",
        "version": 1,
        "target": "Prevention",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 554,
        "name": "mnist_784",
        "version": 1,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 1049,
        "name": "pc4",
        "version": 1,
        "target": "c",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 1050,
        "name": "pc3",
        "version": 1,
        "target": "c",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 1053,
        "name": "jm1",
        "version": 1,
        "target": "defects",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 1063,
        "name": "kc2",
        "version": 1,
        "target": "problems",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 1067,
        "name": "kc1",
        "version": 1,
        "target": "defects",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 1068,
        "name": "pc1",
        "version": 1,
        "target": "defects",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 1590,
        "name": "adult",
        "version": 2,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 4134,
        "name": "Bioresponse",
        "version": 1,
        "target": "target",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 1510,
        "name": "wdbc",
        "version": 1,
        "target": "Class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 1489,
        "name": "phoneme",
        "version": 1,
        "target": "Class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 1494,
        "name": "qsar-biodeg",
        "version": 1,
        "target": "Class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 1497,
        "name": "wall-robot-navigation",
        "version": 1,
        "target": "Class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 1501,
        "name": "semeion",
        "version": 1,
        "target": "Class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 1480,
        "name": "ilpd",
        "version": 1,
        "target": "Class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 1485,
        "name": "madelon",
        "version": 1,
        "target": "Class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 1486,
        "name": "nomao",
        "version": 1,
        "target": "Class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 1487,
        "name": "ozone-level-8hr",
        "version": 1,
        "target": "Class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 1468,
        "name": "cnae-9",
        "version": 1,
        "target": "Class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 1475,
        "name": "first-order-theorem-proving",
        "version": 1,
        "target": "Class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 1462,
        "name": "banknote-authentication",
        "version": 1,
        "target": "Class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 1464,
        "name": "blood-transfusion-service-center",
        "version": 1,
        "target": "Class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 4534,
        "name": "PhishingWebsites",
        "version": 1,
        "target": "Result",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 6332,
        "name": "cylinder-bands",
        "version": 2,
        "target": "band_type",
        "row_id_col": None,
        "ignore_cols": ["timestamp", "cylinder_number"],
    },
    {
        "openml_dataset_id": 1461,
        "name": "bank-marketing",
        "version": 1,
        "target": "Class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 4538,
        "name": "GesturePhaseSegmentationProcessed",
        "version": 1,
        "target": "Phase",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 1478,
        "name": "har",
        "version": 1,
        "target": "Class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 23381,
        "name": "dresses-sales",
        "version": 2,
        "target": "Class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 40499,
        "name": "texture",
        "version": 1,
        "target": "Class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 40668,
        "name": "connect-4",
        "version": 2,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 40966,
        "name": "MiceProtein",
        "version": 4,
        "target": "class",
        "row_id_col": "MouseID",
        "ignore_cols": ["Genotype", "Treatment", "Behavior"],
    },
    {
        "openml_dataset_id": 40982,
        "name": "steel-plates-fault",
        "version": 3,
        "target": "target",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 40994,
        "name": "climate-model-simulation-crashes",
        "version": 4,
        "target": "outcome",
        "row_id_col": None,
        "ignore_cols": ["Study", "Run"],
    },
    {
        "openml_dataset_id": 40983,
        "name": "wilt",
        "version": 2,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 40975,
        "name": "car",
        "version": 3,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 40984,
        "name": "segment",
        "version": 3,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": [
            "region.centroid.col",
            "region.centroid.row",
            "region.pixel.count",
        ],
    },
    {
        "openml_dataset_id": 40979,
        "name": "mfeat-pixel",
        "version": 3,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 40996,
        "name": "Fashion-MNIST",
        "version": 1,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 41027,
        "name": "jungle_chess_2pcs_raw_endgame_complete",
        "version": 1,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 23517,
        "name": "numerai28.6",
        "version": 2,
        "target": "attribute_21",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 40923,
        "name": "Devnagari-Script",
        "version": 1,
        "target": "character",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 40927,
        "name": "CIFAR_10",
        "version": 1,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 40978,
        "name": "Internet-Advertisements",
        "version": 2,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 40670,
        "name": "dna",
        "version": 1,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
    {
        "openml_dataset_id": 40701,
        "name": "churn",
        "version": 1,
        "target": "class",
        "row_id_col": None,
        "ignore_cols": None,
    },
]

openml_df = pd.DataFrame.from_records(openml_dict)
